/**
 * State homeschool record-keeping table. Every number here was verified against an
 * official source (state statute, department of education, or legislature site) on
 * 2026-09-13 — see docs/state-sources.md. All 50 states and DC are covered and verified. Unverified states would carry NO numbers: the app
 * shows the summary with a "confirm with your state" caveat and lets the family set
 * their own target. Laws change; targets are always editable in Settings.
 */

export interface StateInfo {
  code: string;
  name: string;
  requiredDays: number | null;
  requiredHours: number | null;
  hoursNote: string;
  attendanceLog: boolean | null;
  portfolio: boolean | null;
  summary: string;
  source: string;
  verified: boolean;
}

export const STATES: StateInfo[] = [
    {"code": "AL", "name": "Alabama", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours for the church-school option that most Alabama homeschoolers use. The only statutory figure is for the private-tutor option: at least 3 hours a day for 140 days a year, between 8 a.m. and 4 p.m. (Ala. Code 16-28-5). The 180-day / 1,080-hour term in 16-13-231 binds local boards of education, not church schools or tutors.", "attendanceLog": null, "portfolio": false, "summary": "Most families enroll the child in a church school, which ALSDE says it has no authority to license or regulate; there is no state testing, curriculum approval, or portfolio. The separate private-tutor option requires a teaching certificate, filing with the superintendent before starting, 3 hours a day for 140 days, and a daily register of work showing hours and attendance.", "source": "https://www.alabamaachieves.org/knowledge-base/homeschool-faqs/", "verified": true},
    {"code": "AK", "name": "Alaska", "requiredDays": null, "requiredHours": null, "hoursNote": "None. AS 14.30.010(b)(12) exempts a child 'being educated in the child's home by a parent or legal guardian' with no conditions attached. The 180-day school term in AS 14.03.030 applies to school districts, not to a parent-directed homeschool.", "attendanceLog": false, "portfolio": false, "summary": "Nothing must be filed or kept: no notice, no registration, no certificated teacher, no approved curriculum, no records, no testing. Enrolling in a district correspondence program is a separate track that does add an individual learning plan, teacher contact and state testing.", "source": "https://www.akleg.gov/basis/statutes.asp#14.30.010", "verified": true},
  {"code": "AZ", "name": "Arizona", "requiredDays": null, "requiredHours": null, "hoursNote": "No statewide days/hours requirement for homeschools (A.R.S. 15-802).", "attendanceLog": false, "portfolio": false, "summary": "File a one-time affidavit of intent with the county school superintendent and teach reading, grammar, math, social studies and science; no attendance log, portfolio, or testing is required.", "source": "https://www.azleg.gov/ars/15/00802.htm", "verified": true},
  {"code": "AR", "name": "Arkansas", "requiredDays": null, "requiredHours": null, "hoursNote": "No statewide days/hours requirement; annual Notice of Intent due August 15 (A.C.A. 6-15-503).", "attendanceLog": false, "portfolio": false, "summary": "Submit an annual Notice of Intent to the local district by August 15; no attendance log, portfolio, or mandatory testing.", "source": "https://dese.ade.arkansas.gov/Offices/office-of-school-choice-and-parent-empowerment/home-schools/notice-of-intent", "verified": true},
  {"code": "CA", "name": "California", "requiredDays": null, "requiredHours": null, "hoursNote": "No statewide days/hours for home-based private schools filing the Private School Affidavit.", "attendanceLog": true, "portfolio": false, "summary": "Home-based private schools file the annual Private School Affidavit and must keep an attendance register showing every absence of a half day or more (Ed. Code 33190/48222), plus course and faculty records; no portfolio or testing.", "source": "https://www.cde.ca.gov/sp/ps/homeschool.asp", "verified": true},
  {"code": "CO", "name": "Colorado", "requiredDays": 172, "requiredHours": null, "hoursNote": "172 days averaging 4 instructional contact hours per day (C.R.S. 22-33-104.5).", "attendanceLog": true, "portfolio": false, "summary": "File a letter of intent 14 days before starting (renewed annually), keep permanent records of attendance, test/evaluation results and immunizations, and test or evaluate in grades 3, 5, 7, 9 and 11.", "source": "https://ed.cde.state.co.us/choice/homeschool", "verified": true},
  {"code": "CT", "name": "Connecticut", "requiredDays": null, "requiredHours": null, "hoursNote": "No statutory days/hours; CSDE recommends (does not require) an attendance log reflecting days and hours of instruction.", "attendanceLog": false, "portfolio": false, "summary": "Parents must provide equivalent instruction under C.G.S. 10-184; notice of intent, attendance log and portfolio are recommended best practices, not legal requirements.", "source": "https://portal.ct.gov/sde/homeschooling/homeschooling-in-connecticut", "verified": true},
  {"code": "DE", "name": "Delaware", "requiredDays": null, "requiredHours": null, "hoursNote": "No statutory minimum days/hours in 14 Del. C. 2703A/2704; homeschools report enrollment by Sept 30 and end-of-year attendance by July 31.", "attendanceLog": true, "portfolio": false, "summary": "Register the homeschool with DDOE, file enrollment by September 30, and report end-of-year attendance by July 31; no portfolio or testing.", "source": "https://delcode.delaware.gov/title14/c027/sc01/index.html", "verified": true},
  {"code": "DC", "name": "District of Columbia", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours; instruction must be 'thorough, regular ... of sufficient duration' (5-A DCMR 5200).", "attendanceLog": false, "portfolio": true, "summary": "File a Notification of Intent with OSSE by August 15 each year and maintain a portfolio of materials and current work for each child, which OSSE may request to review.", "source": "https://osse.dc.gov/sites/default/files/dc/sites/osse/service_content/attachments/Homeschool%20Frequently%20Asked%20Questions%2012.4.19.pdf", "verified": true},
  {"code": "FL", "name": "Florida", "requiredDays": null, "requiredHours": null, "hoursNote": "Home education programs are expressly excluded from the 'school day' requirement (s. 1002.41, F.S.).", "attendanceLog": false, "portfolio": true, "summary": "File a notice of intent, keep a portfolio (a contemporaneous log of educational activities listing reading materials by title plus samples of work) for 2 years available on 15 days' notice, and submit an annual evaluation.", "source": "http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=1000-1099/1002/Sections/1002.41.html", "verified": true},
  {"code": "GA", "name": "Georgia", "requiredDays": 180, "requiredHours": null, "hoursNote": "180 days per 12-month period, each day at least 4.5 school hours (O.C.G.A. 20-2-690).", "attendanceLog": true, "portfolio": false, "summary": "Submit an annual Declaration of Intent to GaDOE, keep attendance records, write an annual progress assessment report (retain 3 years), and test every 3 years beginning at end of grade 3.", "source": "https://login.community.gadoe.org/documents/georgia-home-school-information-about-home-study-programs", "verified": true},
  {"code": "HI", "name": "Hawaii", "requiredDays": null, "requiredHours": null, "hoursNote": "No minimum days/hours; parent's curriculum record must include start/end dates and the number of hours per week spent on instruction (HAR 8-12-15).", "attendanceLog": true, "portfolio": false, "summary": "Submit Form 4140 or a letter of intent, keep a record of the planned curriculum including hours per week of instruction, submit an annual progress report, and provide standardized test scores in grades 3, 5, 8 and 10.", "source": "https://hawaiipublicschools.org/wp-content/uploads/FAQ-DOE-02-2026.pdf", "verified": true},
  {"code": "ID", "name": "Idaho", "requiredDays": null, "requiredHours": null, "hoursNote": "Instruction must be provided 'during a period in each year equal to that in which the public schools are in session' (Idaho Code 33-202); no fixed number stated.", "attendanceLog": false, "portfolio": false, "summary": "No notice, attendance log, portfolio, or testing is required; parents simply provide instruction in subjects commonly taught in public schools for a period equal to the public school year.", "source": "https://legislature.idaho.gov/statutesrules/idstat/title33/t33ch2/sect33-202/", "verified": true},
  {"code": "IL", "name": "Illinois", "requiredDays": null, "requiredHours": null, "hoursNote": "No requirements for number of school days or length of school day (ISBE).", "attendanceLog": false, "portfolio": false, "summary": "Homeschools operate as private schools with no registration, testing, or record-keeping requirements; ISBE encourages but does not require good records.", "source": "https://www.isbe.net/Documents/Illinois-Homeschooling.pdf", "verified": true},
  {"code": "IN", "name": "Indiana", "requiredDays": 180, "requiredHours": null, "hoursNote": "IDOE: provide 180 days of instruction per academic year (July 1-June 30); no hours-per-day figure.", "attendanceLog": true, "portfolio": false, "summary": "Keep attendance records (IC 20-33-2-20) available on request from the Secretary of Education or superintendent and provide 180 days of instruction; registration and testing are not required.", "source": "https://www.in.gov/doe/files/Homeschool-FAQ-21-08-03.pdf", "verified": true},
  {"code": "IA", "name": "Iowa", "requiredDays": 148, "requiredHours": null, "hoursNote": "Competent Private Instruction: at least 148 days per school year, 37 days per quarter (Iowa Code 299A.1). Independent Private Instruction has no days/hours requirement.", "attendanceLog": false, "portfolio": false, "summary": "Under CPI, file Form A by September 1, provide 148 days of instruction and complete an annual assessment; under IPI, no filing, days, or records beyond a report on request.", "source": "https://www.legis.iowa.gov/docs/code/2025/299A.1.pdf", "verified": true},
    {"code": "KS", "name": "Kansas", "requiredDays": 186, "requiredHours": 1116, "hoursNote": "K.S.A. 72-3120 requires instruction for a period 'substantially equivalent' to the public school term in your district. It sets no number itself; the public-school benchmark it points at is K.S.A. 72-3115, which is 186 days OR 1,116 hours for grades 1-11 (465 hours for kindergarten, 181 days / 1,086 hours for grade 12). Days and hours are alternatives, not both, and your own district's calendar may run longer.", "attendanceLog": false, "portfolio": false, "summary": "Register the non-accredited private school's name and address with the State Board of Education (K.S.A. 72-4346, free online form), teach through a competent instructor, and run a term substantially equivalent to your district's. No approval, curriculum review, attendance log, portfolio, testing or reporting is required.", "source": "https://ksrevisor.gov/statutes/chapters/ch72/072_031_0020.html", "verified": true},
  {"code": "KY", "name": "Kentucky", "requiredDays": 185, "requiredHours": 1062, "hoursNote": "Home schools follow the public-school calendar under KRS 158.080/158.070: minimum term 185 days; student instructional year at least 1,062 hours on not fewer than 170 attendance days.", "attendanceLog": true, "portfolio": false, "summary": "Notify the local superintendent annually, keep attendance and scholarship (grade) reports open to inspection by the director of pupil personnel, and teach for a term equal to public schools.", "source": "https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=56511", "verified": true},
  {"code": "LA", "name": "Louisiana", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours stated on the LDOE home-study page; BESE-approved home study requires an annual application/renewal.", "attendanceLog": false, "portfolio": null, "summary": "Apply to BESE for home-study approval each year; students are exempt from state assessments, and no attendance log is required (evidence of progress is submitted with renewals).", "source": "https://doe.louisiana.gov/topic-pages/louisiana-school-choice/home-study", "verified": true},
  {"code": "ME", "name": "Maine", "requiredDays": 175, "requiredHours": null, "hoursNote": "At least 175 days annually of instruction (20-A M.R.S. 5001-A(3)(A)(4)).", "attendanceLog": false, "portfolio": false, "summary": "File a notice of intent within 10 days, provide 175 days of instruction, and submit an annual assessment (test, certified-teacher review, portfolio review by a support group, or advisory board) by September 1.", "source": "https://legislature.maine.gov/statutes/20-A/title20-Asec5001-A.html", "verified": true},
  {"code": "MD", "name": "Maryland", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours; instruction must be 'regular' and 'of sufficient duration' (COMAR 13A.10.01.01).", "attendanceLog": false, "portfolio": true, "summary": "Notify the local superintendent and maintain a portfolio of instructional materials, reading materials and examples of the child's writings, worksheets, workbooks, creative materials and tests, reviewable up to 3 times a year.", "source": "https://marylandpublicschools.org/about/Documents/DSFSS/SSSP/HomeInstruct/COMAR13A.10.01.01HomeInstructionRegulation2019.pdf", "verified": true},
  {"code": "MA", "name": "Massachusetts", "requiredDays": null, "requiredHours": null, "hoursNote": "No statewide days/hours; each school committee sets its approval policy (Care and Protection of Charles).", "attendanceLog": null, "portfolio": null, "summary": "Obtain advance approval of the home-education plan from the local school committee; periodic assessment and any records are set by district policy rather than statute.", "source": "https://www.doe.mass.edu/homeschool/", "verified": true},
  {"code": "MI", "name": "Michigan", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours for home schools under MCL 380.1561(3)(f).", "attendanceLog": false, "portfolio": false, "summary": "Teach the required subjects; no registration, attendance log, portfolio, or testing is required for home schools under exemption (f).", "source": "https://www.michigan.gov/mde/-/media/Project/Websites/mde/OFM/Grants/NonPublic--Home-Schools/2025-2026-Docs/2025---2026-Nonpublic-and-Homeschool-Manual.pdf", "verified": true},
  {"code": "MN", "name": "Minnesota", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours in Minn. Stat. 120A.22/120A.24.", "attendanceLog": false, "portfolio": false, "summary": "File a letter of intent by October 1, keep documentation (class schedules, copies of instructional materials, assessment methods) and proof of annual testing available on request; no attendance log or work portfolio required.", "source": "https://www.revisor.mn.gov/statutes/cite/120A.24", "verified": true},
    {"code": "MS", "name": "Mississippi", "requiredDays": null, "requiredHours": null, "hoursNote": "None. Miss. Code Ann. 37-13-91 sets no minimum instructional days or hours for a home instruction program; the annual certificate of enrollment is the only affirmative duty it places on families.", "attendanceLog": false, "portfolio": false, "summary": "File the MDE certificate of enrollment with your district's school attendance officer on or before September 15 each year, giving the child's and parent's details and a simple description of the education being provided. No curriculum approval, record-keeping, portfolio or testing is required; a notice of noncompliance gives you 10 days to fix it.", "source": "https://www.mdek12.org/sites/default/files/documents/OAE/OCSA/Docs/home-school---ms-code-37-13-91%20(1).pdf", "verified": true},
  {"code": "MO", "name": "Missouri", "requiredDays": null, "requiredHours": 1000, "hoursNote": "1,000 hours of instruction, at least 600 in reading, language arts, mathematics, social studies and science, with at least 400 of those 600 at the regular home school location (RSMo 167.012).", "attendanceLog": true, "portfolio": true, "summary": "Keep a plan book, diary or other written record of subjects taught and activities, a portfolio of samples of academic work, and a record of evaluations of progress; a daily log showing the 1,000 hours is a defense to prosecution.", "source": "https://revisor.mo.gov/main/OneSection.aspx?section=167.012", "verified": true},
  {"code": "MT", "name": "Montana", "requiredDays": null, "requiredHours": 1080, "hoursNote": "Minimum aggregate hours per MCA 20-1-301: 720 hours grades 1-3; 1,080 hours grades 4-12 (360/720 for half/full-time kindergarten).", "attendanceLog": true, "portfolio": false, "summary": "Notify the county superintendent each school year, maintain pupil attendance records available on request, and provide the minimum aggregate hours of an organized course of study (MCA 20-5-109).", "source": "https://mca.legmt.gov/bills/mca/title_0200/chapter_0050/part_0010/section_0090/0200-0050-0010-0090.html", "verified": true},
  {"code": "NE", "name": "Nebraska", "requiredDays": null, "requiredHours": 1080, "hoursNote": "1,032 hours for elementary (K-8) and 1,080 hours for secondary (9-12) per NDE exempt-school instructions.", "attendanceLog": null, "portfolio": false, "summary": "File the exempt-school election annually with NDE and provide the minimum instructional hours; curriculum, instructor and grade reporting were eliminated by LB1027 (2024), and no testing or portfolio is required.", "source": "https://www.education.ne.gov/wp-content/uploads/2025/06/2526_OL_Instructions.pdf", "verified": true},
  {"code": "NV", "name": "Nevada", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours (NRS 388D.020).", "attendanceLog": false, "portfolio": false, "summary": "File a one-time notice of intent with an educational plan; the plan cannot be used to deny the notice and no attendance log, testing, or portfolio is required.", "source": "https://www.leg.state.nv.us/nrs/nrs-388d.html", "verified": true},
    {"code": "NH", "name": "New Hampshire", "requiredDays": null, "requiredHours": null, "hoursNote": "None. RSA chapter 193-A sets no minimum days or hours, and RSA 193-A:4 says dates and hours of instruction need not coincide with the resident district's calendar.", "attendanceLog": false, "portfolio": false, "summary": "As of July 1, 2026 New Hampshire requires essentially nothing: RSA 193-A:6, which had required a portfolio, reading log and annual evaluation, was repealed and nothing replaced it. Notification is optional except when withdrawing from a public school or to access public school programs. Note the NH DOE website still describes the repealed rules.", "source": "https://gc.nh.gov/rsa/html/XV/193-A/193-A-mrg.htm", "verified": true},
  {"code": "NJ", "name": "New Jersey", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours (N.J.S.A. 18A:38-25 'equivalent instruction').", "attendanceLog": false, "portfolio": false, "summary": "No notice is required except when withdrawing from high school or after a district refuses enrollment; boards may not test the child and are not required to keep a record, so no attendance log or portfolio applies.", "source": "https://www.nj.gov/education/safety/nontraditional/faq_homeschool.shtml", "verified": true},
  {"code": "NM", "name": "New Mexico", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours (NMSA 22-1-2.1).", "attendanceLog": false, "portfolio": false, "summary": "Register with PED within 30 days of starting and by August 1 each year, hold a high school diploma or equivalent, and keep immunization records or waiver; attendance logs and portfolios are encouraged but not required.", "source": "https://webnew.ped.state.nm.us/bureaus/options-parents-families/home-schools/", "verified": true},
  {"code": "NY", "name": "New York", "requiredDays": 180, "requiredHours": 990, "hoursNote": "Substantial equivalent of 180 days; 900 hours per year grades 1-6, 990 hours grades 7-12 (8 NYCRR 100.10(f)).", "attendanceLog": true, "portfolio": false, "summary": "Submit an annual IHIP, keep attendance records available to the district on request, file four quarterly reports documenting hours of instruction, and submit an annual assessment.", "source": "https://www.schools.nyc.gov/docs/default-source/default-document-library/home-school-attendance-calendar.pdf", "verified": true},
  {"code": "NC", "name": "North Carolina", "requiredDays": null, "requiredHours": null, "hoursNote": "Operate on a regular schedule for at least nine calendar months per year; no statutory hours (DNPE recommends 5 hours/day).", "attendanceLog": true, "portfolio": false, "summary": "File a Notice of Intent with DNPE, keep annual attendance and immunization records for each student, and administer a nationally standardized test each year (keep results at least one year).", "source": "https://www.doa.nc.gov/divisions/non-public-education/home-schools/requirements-recommendations", "verified": true},
  {"code": "ND", "name": "North Dakota", "requiredDays": 175, "requiredHours": null, "hoursNote": "At least 4 hours per day for at least 175 days per year (NDCC 15.1-23).", "attendanceLog": false, "portfolio": false, "summary": "File a statement of intent annually (5 days before starting), provide 175 days of at least 4 hours, keep an annual record of courses and academic progress assessments, and test in grades 4, 6, 8 and 10 unless exempt.", "source": "https://www.nd.gov/dpi/parentscommunity/parents/home-education", "verified": true},
  {"code": "OH", "name": "Ohio", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours under R.C. 3321.042 (effective 2023).", "attendanceLog": false, "portfolio": false, "summary": "Send an annual notice to the district superintendent by August 30 (or within 5 days of starting) with an assurance the required subjects will be taught; no hours, attendance log, portfolio, or assessment is required.", "source": "https://codes.ohio.gov/ohio-revised-code/section-3321.042", "verified": true},
  {"code": "OK", "name": "Oklahoma", "requiredDays": 180, "requiredHours": null, "hoursNote": "OSDE: 180 days per calendar year and six clock hours (360 minutes) per day.", "attendanceLog": false, "portfolio": false, "summary": "Homeschools are unregulated and need not register; OSDE advises 180 days of six hours and says parents must document compliance only if the child re-enters public school.", "source": "https://oklahoma.gov/education/services/school-choice/home-school.html", "verified": true},
  {"code": "OR", "name": "Oregon", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours (ORS 339.035).", "attendanceLog": false, "portfolio": false, "summary": "Notify the ESD within 10 days of starting and have the child tested after grades 3, 5, 8 and 10; no attendance log or portfolio (a portfolio is only an option for interscholastic eligibility).", "source": "https://www.oregon.gov/ode/learning-options/homeschool/pages/infoforfamilies.aspx", "verified": true},
  {"code": "PA", "name": "Pennsylvania", "requiredDays": 180, "requiredHours": 990, "hoursNote": "180 days or 900 hours (elementary) / 990 hours (secondary) of instruction (24 P.S. 13-1327.1).", "attendanceLog": true, "portfolio": true, "summary": "File an annual affidavit, keep a portfolio with a contemporaneous log of reading materials by title and samples of writings, worksheets, workbooks and creative materials, plus test results in grades 3, 5 and 8, and submit an evaluator's certification by June 30.", "source": "https://www.pa.gov/content/dam/copapwp-pagov/en/education/documents/instruction/home-education-and-private-tutoring/home%20education%20and%20private%20tutoring%20guide.pdf", "verified": true},
  {"code": "RI", "name": "Rhode Island", "requiredDays": null, "requiredHours": 1080, "hoursNote": "RIDE: instruction 'substantially equal' to public schools, currently 1,080 hours (about 5.5 hours for 180 days); schedule need not match the district calendar.", "attendanceLog": true, "portfolio": false, "summary": "Obtain local school committee approval, keep an attendance register that is returned to the school committee, and agree with the district on a method of evaluating progress.", "source": "https://ride.ri.gov/students-families/education-programs/home-schooling", "verified": true},
  {"code": "SC", "name": "South Carolina", "requiredDays": 180, "requiredHours": null, "hoursNote": "Instructional year of at least 180 days; school day at least 4.5 hours excluding lunch and recess (S.C. Code 59-65-40/-45/-47).", "attendanceLog": true, "portfolio": true, "summary": "Under all three options keep a plan book, diary or other record of subjects taught and activities, a portfolio of samples of academic work, and a semiannual progress report including attendance records.", "source": "https://www.scstatehouse.gov/code/t59c065.php", "verified": true},
  {"code": "SD", "name": "South Dakota", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours specified by SD DOE for alternative instruction (SDCL 13-27-3).", "attendanceLog": false, "portfolio": false, "summary": "File an alternative-instruction notification within 30 days of starting; standardized testing was eliminated by SB 177 (2021) and attendance/grade records are recommended, not required.", "source": "https://doe.sd.gov/oatq/documents/HS-SDAltInst-FAQ.pdf", "verified": true},
  {"code": "TN", "name": "Tennessee", "requiredDays": 180, "requiredHours": null, "hoursNote": "Four hours per day for 180 days (T.C.A. 49-6-3050).", "attendanceLog": true, "portfolio": false, "summary": "File an intent to home school with the district each year, keep attendance records and report attendance to the district, and present the student for testing in grades 5, 7 and 9.", "source": "https://www.tn.gov/content/dam/tn/education/nonpublic/Frequently_Asked_Questions_Home_School.pdf", "verified": true},
  {"code": "TX", "name": "Texas", "requiredDays": null, "requiredHours": null, "hoursNote": "No statewide days/hours; home schools are private schools (Leeper).", "attendanceLog": false, "portfolio": false, "summary": "Follow a course of study including good citizenship; no notice, attendance log, portfolio, or testing is required.", "source": "https://tea.texas.gov/texas-schools/general-information/finding-a-school-for-your-child/home-schooling", "verified": true},
  {"code": "UT", "name": "Utah", "requiredDays": null, "requiredHours": null, "hoursNote": "Districts may not require set hours or days (Utah Code 53G-6-204).", "attendanceLog": false, "portfolio": false, "summary": "Give a one-time notification to the local school board; the district may not require attendance records, records of instruction, curriculum, hours, or testing.", "source": "https://schools.utah.gov/parent/homeschool", "verified": true},
  {"code": "VT", "name": "Vermont", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours; at least 60% of core academics must occur at home (16 V.S.A. 166b).", "attendanceLog": false, "portfolio": null, "summary": "Send an enrollment notice to the Agency of Education with a minimum course of study and submit an end-of-year assessment (teacher assessment, report with portfolio, portfolio of 4-6 samples per subject, or approved test).", "source": "https://education.vermont.gov/sites/aoe/files/documents/edu-home-study-guidelines-11-13-2019.pdf", "verified": true},
  {"code": "VA", "name": "Virginia", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours (Va. Code 22.1-254.1).", "attendanceLog": false, "portfolio": null, "summary": "File a notice of intent by August 15 with a curriculum description and provide evidence of progress by August 1 (standardized test at or above the 4th stanine, or an evaluation letter/portfolio review by a qualified evaluator).", "source": "https://law.lis.virginia.gov/vacode/title22.1/chapter14/section22.1-254.1/", "verified": true},
  {"code": "WA", "name": "Washington", "requiredDays": null, "requiredHours": 1000, "hoursNote": "Hours equivalent to approved private schools: school-wide annual average of 1,000 hours for grades 1-12 and 450 hours for kindergarten (RCW 28A.225.010(4), 28A.195.010).", "attendanceLog": false, "portfolio": false, "summary": "File an annual declaration of intent by September 15, administer an annual test or certified-teacher assessment, and keep those results and immunization records for forwarding if the child enrolls elsewhere.", "source": "https://app.leg.wa.gov/rcw/default.aspx?cite=28A.225.010", "verified": true},
  {"code": "WV", "name": "West Virginia", "requiredDays": 180, "requiredHours": null, "hoursNote": "Instruction for a time equal to the public instructional term in W. Va. Code 18-5-45: 180 separate instructional days (or equivalent time).", "attendanceLog": false, "portfolio": null, "summary": "File a notice of intent, obtain an annual academic assessment (test, state testing, certified-teacher portfolio review, or agreed alternative), submit results in grades 3, 5, 8 and 11 by June 30, and keep assessment copies for 3 years.", "source": "https://code.wvlegislature.gov/18-8-1/", "verified": true},
  {"code": "WI", "name": "Wisconsin", "requiredDays": null, "requiredHours": 875, "hoursNote": "At least 875 hours of instruction each school year (Wis. Stat. 118.165).", "attendanceLog": false, "portfolio": false, "summary": "File the PI-1206 Homeschool Enrollment Report annually and provide 875 hours of a sequentially progressive curriculum in six subjects; no attendance log, portfolio, or testing is required.", "source": "https://dpi.wi.gov/sms/home-based", "verified": true},
  {"code": "WY", "name": "Wyoming", "requiredDays": null, "requiredHours": null, "hoursNote": "No days/hours stated by WDE; curriculum submission to the district was eliminated July 1, 2025 (HB 46).", "attendanceLog": false, "portfolio": false, "summary": "Provide a sequentially progressive curriculum in the basic subjects and meet with a district counselor/administrator to withdraw; no attendance log, portfolio, or testing is required.", "source": "https://edu.wyoming.gov/parents/homeschooling/", "verified": true},
];

export function getState(code: string): StateInfo | undefined {
  return STATES.find((s) => s.code === code);
}
